services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_prod
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage_prod:/home/node/.n8n
    networks:
      - caddy_network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

volumes:
  n8n_storage_prod:

networks:
  caddy_network:
    external: true